### ISSUE TITLE
cant load kzrockthevote.smx with gokz

### ISSUE THREAD

**Issue by 0xmizu** [1zc/KZ-MapChooser#2]
rtv doesn't work however nominate does.
everything is updated and setup following gokz guides...

```
sm_rcon sm plugins load kzrockthevote.smx
[SM] Plugin kzrockthevote.smx failed to load: Could not find required plugin "KZTimer".

Errors:
kzrockthevote.smx (KZ Rock The Vote): Could not find required plugin "KZTimer"
mizu : rtv
```

**Comment by 1zc** [comment]
@0xmizu Could you give this package a shot? It should resolve the issue you're facing. I hadn't tested this with GOKZ, hence I had forgotten to make the KZT rank requirement feature in the RTV plugin optional - i.e, have it disable itself if KZTimer wasn't being used.

[KZ-MCv2.0.1-30DEC.zip](https://github.com/1zc/KZ-MapChooser/files/5753560/KZ-MCv2.0.1-30DEC.zip)

**Comment by 0xmizu** [comment]
Thanks ^ that pack works...
amazing work <3
